version: "3"

services:
  api:
    build:
      dockerfile: dockerfiles/api/Dockerfile
      context: $GOPATH/src/github.com/devandcoffee/stapp
    container_name: stapp_api
    ports:
      - 8080:8080
