version: "3.3"

services:
  api:
    build: dockerfiles/api/Dockerfile
    container_name: stapp_api
    hostname: api
    ports:
      - 8080:8080
    volumes:
      - ./:/go/src/github.com/devandcoffee/stapp/
    command:
      ["./wait-for-it.sh", "db:5432", "--", "go", "run", "server/main.go"]
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: stapp_db
    hostname: db
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: stdb
      POSTGRES_USER: stadmin
    volumes:
      - ~/.docker/stapp-data:/var/lib/postgresql/data
